### ISSUE TITLE
Doesn't build with gcc 5

### ISSUE THREAD

**Issue by marillat** [kodi-pvr/pvr.argustv#27]
Hi,
The Isengard branch fail to build with gcc 5.2.1 and arches different than i386 or amd64 (armhf, powerpc, armel)

src/uri.cpp:44:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:65:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:86:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:107:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:128:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
