### PR TITLE
Sync enum representation of char_class_e in struct traits with definition

### LINKED ISSUE #27: Doesn't build with gcc 5
Hi,
The Isengard branch fail to build with gcc 5.2.1 and arches different than i386 or amd64 (armhf, powerpc, armel)

src/uri.cpp:44:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:65:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:86:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:107:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
src/uri.cpp:128:3: error: narrowing conversion of ‘(uri::char_class_e)-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]

### PR DESCRIPTION
**Pull request by rbalint**
This fixes #27 breaking the build on many Debian architectures.

### CODE REVIEW

**Comment by rbalint** [comment]
Please also cherry-pick to other addons like nextpvr and mediaportal.tvserver.

**Comment by Jalle19** [comment]
Can you make the necessary PRs?

**Comment by rbalint** [comment]
@Jalle19 Sure, after this one got accepted to be sure that this is the preferred fix. :-)

**Comment by margro** [comment]
Did a quick compile test under Windows and this change works fine in VS2013.
For the corresponding change for pvr.mediaportal.tvserver, see PR 28.
